[build-system]
requires = ["setuptools>=61.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "amazonml_len_pred"
version = "0.1.0"
description = "Amazon Product Length Prediction solution"
requires-python = ">=3.10"
dependencies = [
    "numpy",
    "pandas",
    "scipy",
    "scikit-learn",
    "pyyaml",
    "joblib",
    "matplotlib",
    "lightgbm",
    "pytest",
    "torch",
    "transformers"
]
